// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyG00f4-w2fasvEX6Ura-GocIPsGilAFc',
    appId: '1:630194290251:web:c6c0d15549bc255ae957ce',
    messagingSenderId: '630194290251',
    projectId: 'storepool-zi3',
    authDomain: 'storepool-zi3.firebaseapp.com',
    storageBucket: 'storepool-zi3.firebasestorage.app',
    measurementId: 'G-JSZHEH6P6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC6qkVbLpfFcbgL9RGn--fMaLPzMaXoHo',
    appId: '1:630194290251:android:ce772d2feaec6d2fe957ce',
    messagingSenderId: '630194290251',
    projectId: 'storepool-zi3',
    storageBucket: 'storepool-zi3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeg5MWQUTpsydVBQL5WLcDG2U8RHCDldw',
    appId: '1:630194290251:ios:4ee20b00234bb9dee957ce',
    messagingSenderId: '630194290251',
    projectId: 'storepool-zi3',
    storageBucket: 'storepool-zi3.firebasestorage.app',
    iosBundleId: 'com.example.storepool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeg5MWQUTpsydVBQL5WLcDG2U8RHCDldw',
    appId: '1:630194290251:ios:4ee20b00234bb9dee957ce',
    messagingSenderId: '630194290251',
    projectId: 'storepool-zi3',
    storageBucket: 'storepool-zi3.firebasestorage.app',
    iosBundleId: 'com.example.storepool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyG00f4-w2fasvEX6Ura-GocIPsGilAFc',
    appId: '1:630194290251:web:f804b3806cebe84de957ce',
    messagingSenderId: '630194290251',
    projectId: 'storepool-zi3',
    authDomain: 'storepool-zi3.firebaseapp.com',
    storageBucket: 'storepool-zi3.firebasestorage.app',
    measurementId: 'G-H4F0X4J2MR',
  );
}
